# Generated by Django 5.0.6 on 2024-06-15 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voiture',
            old_name='sulg',
            new_name='slug',
        ),
    ]
